apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intfact
  annotations:
    github.com/project-slug: ghhenry/intfact
spec:
  type: library
  lifecycle: experimental
  owner: guests
